schema: ./strapi/exports/**/*.graphql
documents: www/src/**/*.graphql
extensions:
  codegen:
    generates:
      www/src/app/graphql.tsx:
        config:
          withComponent: false
          withHOC: false
          withHooks: true
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
        documents: 'www/src/**/*.{graphql,gql}'
    overwrite: true
