name: CI + Production Deploy

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ^12

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Reuse cached node_modules
        uses: actions/cache@v2.1.3
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            strapi/node_modules
            www/node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Reuse strapi build caches
        uses: actions/cache@v2.1.3
        with:
          path: |
            strapi/.cache
            strapi/build
          key: strapi-${{ hashFiles('strapi/**/*') }}

      - name: Reuse www build caches
        uses: actions/cache@v2.1.3
        with:
          path: |
            www/.cache
            www/public
          key: www-${{ hashFiles('www/gatsby-*') }}

      - name: yarn install
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: yarn build
        run: yarn build
        env:
          NODE_ENV: production
          CI: true
          GATSBY_GRAPHQL_URL: ${{ secrets.GATSBY_GRAPHQL_URL }}
          GATSBY_STRAPI_API_BASE: ${{ secrets.GATSBY_STRAPI_API_BASE }}
          GATSBY_CONTACT_EMAIL_TO: ${{ secrets.GATSBY_CONTACT_EMAIL_TO}}
          GATSBY_YOUTUBE_PLAYLIST_ID: ${{ secrets.GATSBY_YOUTUBE_PLAYLIST_ID}}
          GATSBY_YOUTUBE_API_KEY: ${{ secrets.GATSBY_YOUTUBE_API_KEY}}

      - name: yarn test
        run: yarn test
        env:
          NODE_ENV: production
          CI: true
          GATSBY_GRAPHQL_URL: ${{ secrets.GATSBY_GRAPHQL_URL }}
          GATSBY_STRAPI_API_BASE: ${{ secrets.GATSBY_STRAPI_API_BASE }}
          GATSBY_CONTACT_EMAIL_TO: ${{ secrets.GATSBY_CONTACT_EMAIL_TO}}
          GATSBY_YOUTUBE_PLAYLIST_ID: ${{ secrets.GATSBY_YOUTUBE_PLAYLIST_ID}}
          GATSBY_YOUTUBE_API_KEY: ${{ secrets.GATSBY_YOUTUBE_API_KEY}}

      - name: Deploy strapi on Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: 'strapi'
        env:
          NODE_ENV: production
          CI: true
          CD: true

      - name: Deploy www/public to Vercel
        uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: --prod
          working-directory: www/public/
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
